/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端相关资料",
  "description": "前端相关资料",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/svg/favicon.svg"
      }
    ],
    [
      "meta",
      {
        "name": "referrer",
        "content": "no-referrer"
      }
    ]
  ],
  "pages": [
    {
      "title": "XYZCY",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-c4639e1a",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "js",
          "slug": "js"
        },
        {
          "level": 2,
          "title": "css",
          "slug": "css"
        },
        {
          "level": 2,
          "title": "vue",
          "slug": "vue"
        },
        {
          "level": 2,
          "title": "性能优化",
          "slug": "性能优化"
        },
        {
          "level": 2,
          "title": "网络",
          "slug": "网络"
        },
        {
          "level": 2,
          "title": "学习资料",
          "slug": "学习资料"
        }
      ]
    },
    {
      "title": "常用数组操作方法",
      "frontmatter": {},
      "regularPath": "/handbook/Array/Array.html",
      "relativePath": "handbook/Array/Array.md",
      "key": "v-4bbdba36",
      "path": "/handbook/Array/Array.html",
      "headers": [
        {
          "level": 2,
          "title": "常用数组操作方法",
          "slug": "常用数组操作方法"
        }
      ]
    },
    {
      "title": "闭包",
      "frontmatter": {},
      "regularPath": "/handbook/Closure/Closure.html",
      "relativePath": "handbook/Closure/Closure.md",
      "key": "v-2e6072ee",
      "path": "/handbook/Closure/Closure.html",
      "headers": [
        {
          "level": 2,
          "title": "闭包",
          "slug": "闭包"
        },
        {
          "level": 2,
          "title": "函数参数传递方式：按值传递",
          "slug": "函数参数传递方式-按值传递"
        }
      ]
    },
    {
      "title": "防抖",
      "frontmatter": {},
      "regularPath": "/handbook/Debounce/Debounce.html",
      "relativePath": "handbook/Debounce/Debounce.md",
      "key": "v-42e99924",
      "path": "/handbook/Debounce/Debounce.html",
      "headers": [
        {
          "level": 2,
          "title": "防抖",
          "slug": "防抖"
        },
        {
          "level": 2,
          "title": "节流",
          "slug": "节流"
        }
      ]
    },
    {
      "title": "事件循环",
      "frontmatter": {},
      "regularPath": "/handbook/EventLoop/EventLoop.html",
      "relativePath": "handbook/EventLoop/EventLoop.md",
      "key": "v-063fbda2",
      "path": "/handbook/EventLoop/EventLoop.html",
      "headers": [
        {
          "level": 2,
          "title": "事件循环",
          "slug": "事件循环"
        },
        {
          "level": 2,
          "title": "async/await相关",
          "slug": "async-await相关"
        }
      ]
    },
    {
      "title": "Promise",
      "frontmatter": {},
      "regularPath": "/handbook/EventLoop/Promise.html",
      "relativePath": "handbook/EventLoop/Promise.md",
      "key": "v-d06536b0",
      "path": "/handbook/EventLoop/Promise.html",
      "headers": [
        {
          "level": 2,
          "title": "Promise",
          "slug": "promise"
        }
      ]
    },
    {
      "title": "变量对象",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/ActivationObject.html",
      "relativePath": "handbook/ExecutionContext/ActivationObject.md",
      "key": "v-2c40d1a8",
      "path": "/handbook/ExecutionContext/ActivationObject.html",
      "headers": [
        {
          "level": 2,
          "title": "变量对象",
          "slug": "变量对象"
        },
        {
          "level": 2,
          "title": "暂时性死区",
          "slug": "暂时性死区"
        }
      ]
    },
    {
      "title": "执行上下文",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/ExecutionContext.html",
      "relativePath": "handbook/ExecutionContext/ExecutionContext.md",
      "key": "v-de4c4eb8",
      "path": "/handbook/ExecutionContext/ExecutionContext.html",
      "headers": [
        {
          "level": 2,
          "title": "执行上下文",
          "slug": "执行上下文"
        },
        {
          "level": 2,
          "title": "执行上下文栈",
          "slug": "执行上下文栈"
        }
      ]
    },
    {
      "title": "作用域链",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/Scope.html",
      "relativePath": "handbook/ExecutionContext/Scope.md",
      "key": "v-5252a1c8",
      "path": "/handbook/ExecutionContext/Scope.html",
      "headers": [
        {
          "level": 2,
          "title": "作用域链",
          "slug": "作用域链"
        }
      ]
    },
    {
      "title": "This",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/This.html",
      "relativePath": "handbook/ExecutionContext/This.md",
      "key": "v-293445d6",
      "path": "/handbook/ExecutionContext/This.html",
      "headers": [
        {
          "level": 2,
          "title": "This",
          "slug": "this"
        },
        {
          "level": 2,
          "title": "call、apply、bind",
          "slug": "call、apply、bind"
        }
      ]
    },
    {
      "title": "继承",
      "frontmatter": {},
      "regularPath": "/handbook/Prototype/Inherit.html",
      "relativePath": "handbook/Prototype/Inherit.md",
      "key": "v-e75c1140",
      "path": "/handbook/Prototype/Inherit.html",
      "headers": [
        {
          "level": 2,
          "title": "继承",
          "slug": "继承"
        },
        {
          "level": 2,
          "title": "class继承",
          "slug": "class继承"
        }
      ]
    },
    {
      "title": "操作符优先级",
      "frontmatter": {},
      "regularPath": "/handbook/Operator/Operator.html",
      "relativePath": "handbook/Operator/Operator.md",
      "key": "v-972de738",
      "path": "/handbook/Operator/Operator.html",
      "headers": [
        {
          "level": 2,
          "title": "操作符优先级",
          "slug": "操作符优先级"
        }
      ]
    },
    {
      "title": "原型",
      "frontmatter": {},
      "regularPath": "/handbook/Prototype/Prototype.html",
      "relativePath": "handbook/Prototype/Prototype.md",
      "key": "v-3c5dfe92",
      "path": "/handbook/Prototype/Prototype.html",
      "headers": [
        {
          "level": 2,
          "title": "原型",
          "slug": "原型"
        }
      ]
    },
    {
      "title": "前端路由",
      "frontmatter": {},
      "regularPath": "/handbook/Router/Router.html",
      "relativePath": "handbook/Router/Router.md",
      "key": "v-4a7e9064",
      "path": "/handbook/Router/Router.html",
      "headers": [
        {
          "level": 2,
          "title": "前端路由",
          "slug": "前端路由"
        }
      ]
    },
    {
      "title": "TCP协议",
      "frontmatter": {},
      "regularPath": "/handbook/Render/Render.html",
      "relativePath": "handbook/Render/Render.md",
      "key": "v-25a0c1a4",
      "path": "/handbook/Render/Render.html",
      "headers": [
        {
          "level": 2,
          "title": "TCP协议",
          "slug": "tcp协议"
        },
        {
          "level": 2,
          "title": "UDP协议",
          "slug": "udp协议"
        },
        {
          "level": 2,
          "title": "HTTP协议",
          "slug": "http协议"
        },
        {
          "level": 2,
          "title": "URL",
          "slug": "url"
        },
        {
          "level": 2,
          "title": "DNS",
          "slug": "dns"
        },
        {
          "level": 2,
          "title": "页面渲染",
          "slug": "页面渲染"
        },
        {
          "level": 2,
          "title": "回流和重绘",
          "slug": "回流和重绘"
        },
        {
          "level": 3,
          "title": "回流",
          "slug": "回流"
        },
        {
          "level": 3,
          "title": "重绘",
          "slug": "重绘"
        },
        {
          "level": 3,
          "title": "如何避免触发回流和重绘",
          "slug": "如何避免触发回流和重绘"
        },
        {
          "level": 2,
          "title": "性能优化",
          "slug": "性能优化"
        }
      ]
    },
    {
      "title": "常用字符串操作方法",
      "frontmatter": {},
      "regularPath": "/handbook/String/String.html",
      "relativePath": "handbook/String/String.md",
      "key": "v-6239f264",
      "path": "/handbook/String/String.html",
      "headers": [
        {
          "level": 2,
          "title": "常用字符串操作方法",
          "slug": "常用字符串操作方法"
        }
      ]
    },
    {
      "title": "原始值和引用值",
      "frontmatter": {},
      "regularPath": "/handbook/Type/Type.html",
      "relativePath": "handbook/Type/Type.md",
      "key": "v-3ed41a64",
      "path": "/handbook/Type/Type.html",
      "headers": [
        {
          "level": 2,
          "title": "原始值和引用值",
          "slug": "原始值和引用值"
        },
        {
          "level": 2,
          "title": "其它数据类型转布尔值",
          "slug": "其它数据类型转布尔值"
        },
        {
          "level": 2,
          "title": "原始值转字符串",
          "slug": "原始值转字符串"
        },
        {
          "level": 2,
          "title": "原始值转数字",
          "slug": "原始值转数字"
        },
        {
          "level": 2,
          "title": "原始值转对象",
          "slug": "原始值转对象"
        },
        {
          "level": 3,
          "title": "String对象",
          "slug": "string对象"
        },
        {
          "level": 3,
          "title": "基本类型的包装对象",
          "slug": "基本类型的包装对象"
        },
        {
          "level": 3,
          "title": "Object()",
          "slug": "object"
        },
        {
          "level": 2,
          "title": "toString()",
          "slug": "tostring"
        },
        {
          "level": 2,
          "title": "valueOf()",
          "slug": "valueof"
        },
        {
          "level": 2,
          "title": "toPrimitive",
          "slug": "toprimitive"
        },
        {
          "level": 2,
          "title": "对象转数字",
          "slug": "对象转数字"
        },
        {
          "level": 2,
          "title": "对象转字符串",
          "slug": "对象转字符串"
        },
        {
          "level": 2,
          "title": "Symbol.toPrimitive",
          "slug": "symbol-toprimitive"
        },
        {
          "level": 2,
          "title": "使用==比较时的类型转换",
          "slug": "使用-比较时的类型转换"
        },
        {
          "level": 2,
          "title": "+、-、*、/、%的类型转换",
          "slug": "、-、-、-、-的类型转换"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "xyzcy的 个人网站",
        "link": "http://47.111.22.150:8099/"
      },
      {
        "text": "Gitee",
        "link": "https://gitee.com/xyzcy"
      }
    ],
    "sidebar": [
      {
        "title": "欢迎浏览",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "前言",
            "path": "/"
          }
        ]
      },
      {
        "title": "原型与原型链",
        "path": "/handbook/Prototype/Prototype",
        "collapsable": false,
        "children": [
          {
            "title": "原型",
            "path": "/handbook/Prototype/Prototype"
          },
          {
            "title": "继承",
            "path": "/handbook/Prototype/Inherit"
          }
        ]
      },
      {
        "title": "执行上下文",
        "path": "/handbook/ExecutionContext/ExecutionContext",
        "collapsable": false,
        "children": [
          {
            "title": "执行上下文",
            "path": "/handbook/ExecutionContext/ExecutionContext"
          },
          {
            "title": "变量对象",
            "path": "/handbook/ExecutionContext/ActivationObject"
          },
          {
            "title": "作用域链",
            "path": "/handbook/ExecutionContext/Scope"
          },
          {
            "title": "This",
            "path": "/handbook/ExecutionContext/This"
          }
        ]
      },
      {
        "title": "闭包",
        "path": "/handbook/Closure/Closure",
        "collapsable": false,
        "children": [
          {
            "title": "闭包",
            "path": "/handbook/Closure/Closure"
          }
        ]
      },
      {
        "title": "事件循环",
        "path": "/handbook/EventLoop/EventLoop",
        "collapsable": false,
        "children": [
          {
            "title": "事件循环",
            "path": "/handbook/EventLoop/EventLoop"
          },
          {
            "title": "Promise",
            "path": "/handbook/EventLoop/Promise"
          }
        ]
      },
      {
        "title": "常用数组操作方法",
        "path": "/handbook/Array/Array",
        "collapsable": false,
        "children": [
          {
            "title": "常用数组操作方法",
            "path": "/handbook/Array/Array"
          }
        ]
      },
      {
        "title": "常用字符串操作方法",
        "path": "/handbook/String/String",
        "collapsable": false,
        "children": [
          {
            "title": "常用字符串操作方法",
            "path": "/handbook/String/String"
          }
        ]
      },
      {
        "title": "操作符优先级",
        "path": "/handbook/Operator/Operator",
        "collapsable": false,
        "children": [
          {
            "title": "操作符优先级",
            "path": "/handbook/Operator/Operator"
          }
        ]
      },
      {
        "title": "类型转换",
        "path": "/handbook/Type/Type",
        "collapsable": false,
        "children": [
          {
            "title": "类型转换",
            "path": "/handbook/Type/Type"
          }
        ]
      },
      {
        "title": "防抖、节流",
        "path": "/handbook/Debounce/Debounce",
        "collapsable": false,
        "children": [
          {
            "title": "防抖、节流",
            "path": "/handbook/Debounce/Debounce"
          }
        ]
      },
      {
        "title": "浏览器、渲染机制",
        "path": "/handbook/Render/Render",
        "collapsable": false,
        "children": [
          {
            "title": "浏览器、页面渲染",
            "path": "/handbook/Render/Render"
          }
        ]
      },
      {
        "title": "前端路由",
        "path": "/handbook/Router/Router",
        "collapsable": false,
        "children": [
          {
            "title": "前端路由",
            "path": "/handbook/Router/Router"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}