/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "前端相关资料",
  "description": "前端相关资料",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/svg/favicon.svg"
      }
    ],
    [
      "meta",
      {
        "name": "referrer",
        "content": "no-referrer"
      }
    ]
  ],
  "pages": [
    {
      "title": "XYZCY",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-c4639e1a",
      "path": "/"
    },
    {
      "title": "闭包",
      "frontmatter": {},
      "regularPath": "/handbook/Closure/Closure.html",
      "relativePath": "handbook/Closure/Closure.md",
      "key": "v-2e6072ee",
      "path": "/handbook/Closure/Closure.html"
    },
    {
      "title": "常用数组操作方法",
      "frontmatter": {},
      "regularPath": "/handbook/Array/Array.html",
      "relativePath": "handbook/Array/Array.md",
      "key": "v-4bbdba36",
      "path": "/handbook/Array/Array.html"
    },
    {
      "title": "数据类型转换",
      "frontmatter": {},
      "regularPath": "/handbook/DataType/DataType.html",
      "relativePath": "handbook/DataType/DataType.md",
      "key": "v-10861738",
      "path": "/handbook/DataType/DataType.html"
    },
    {
      "title": "事件循环",
      "frontmatter": {},
      "regularPath": "/handbook/EventLoop/EventLoop.html",
      "relativePath": "handbook/EventLoop/EventLoop.md",
      "key": "v-063fbda2",
      "path": "/handbook/EventLoop/EventLoop.html"
    },
    {
      "title": "Promise",
      "frontmatter": {},
      "regularPath": "/handbook/EventLoop/Promise.html",
      "relativePath": "handbook/EventLoop/Promise.md",
      "key": "v-d06536b0",
      "path": "/handbook/EventLoop/Promise.html"
    },
    {
      "title": "执行上下文",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/ExecutionContext.html",
      "relativePath": "handbook/ExecutionContext/ExecutionContext.md",
      "key": "v-de4c4eb8",
      "path": "/handbook/ExecutionContext/ExecutionContext.html"
    },
    {
      "title": "变量对象",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/ActivationObject.html",
      "relativePath": "handbook/ExecutionContext/ActivationObject.md",
      "key": "v-2c40d1a8",
      "path": "/handbook/ExecutionContext/ActivationObject.html"
    },
    {
      "title": "作用域链",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/Scope.html",
      "relativePath": "handbook/ExecutionContext/Scope.md",
      "key": "v-5252a1c8",
      "path": "/handbook/ExecutionContext/Scope.html"
    },
    {
      "title": "操作符优先级",
      "frontmatter": {},
      "regularPath": "/handbook/Operator/Operator.html",
      "relativePath": "handbook/Operator/Operator.md",
      "key": "v-972de738",
      "path": "/handbook/Operator/Operator.html"
    },
    {
      "title": "This",
      "frontmatter": {},
      "regularPath": "/handbook/ExecutionContext/This.html",
      "relativePath": "handbook/ExecutionContext/This.md",
      "key": "v-293445d6",
      "path": "/handbook/ExecutionContext/This.html"
    },
    {
      "title": "原型",
      "frontmatter": {},
      "regularPath": "/handbook/Prototype/Prototype.html",
      "relativePath": "handbook/Prototype/Prototype.md",
      "key": "v-3c5dfe92",
      "path": "/handbook/Prototype/Prototype.html"
    },
    {
      "title": "继承",
      "frontmatter": {},
      "regularPath": "/handbook/Prototype/Inherit.html",
      "relativePath": "handbook/Prototype/Inherit.md",
      "key": "v-e75c1140",
      "path": "/handbook/Prototype/Inherit.html"
    },
    {
      "title": "前端路由",
      "frontmatter": {},
      "regularPath": "/handbook/Router/Router.html",
      "relativePath": "handbook/Router/Router.md",
      "key": "v-4a7e9064",
      "path": "/handbook/Router/Router.html"
    },
    {
      "title": "常用字符串操作方法",
      "frontmatter": {},
      "regularPath": "/handbook/String/String.html",
      "relativePath": "handbook/String/String.md",
      "key": "v-6239f264",
      "path": "/handbook/String/String.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "subSidebar": "auto",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "xyzcy的 个人网站",
        "link": "http://47.111.22.150:8099/"
      },
      {
        "text": "Gitee",
        "link": "https://gitee.com/xyzcy"
      }
    ],
    "sidebar": [
      {
        "title": "欢迎浏览",
        "path": "/",
        "collapsable": false,
        "children": [
          {
            "title": "前言",
            "path": "/"
          }
        ]
      },
      {
        "title": "原型与原型链",
        "path": "/handbook/Prototype/Prototype",
        "collapsable": false,
        "children": [
          {
            "title": "原型",
            "path": "/handbook/Prototype/Prototype"
          },
          {
            "title": "继承",
            "path": "/handbook/Prototype/Inherit"
          }
        ]
      },
      {
        "title": "执行上下文",
        "path": "/handbook/ExecutionContext/ExecutionContext",
        "collapsable": false,
        "children": [
          {
            "title": "执行上下文",
            "path": "/handbook/ExecutionContext/ExecutionContext"
          },
          {
            "title": "变量对象",
            "path": "/handbook/ExecutionContext/ActivationObject"
          },
          {
            "title": "作用域链",
            "path": "/handbook/ExecutionContext/Scope"
          },
          {
            "title": "this",
            "path": "/handbook/ExecutionContext/This"
          }
        ]
      },
      {
        "title": "闭包",
        "path": "/handbook/Closure/Closure",
        "collapsable": false,
        "children": [
          {
            "title": "闭包",
            "path": "/handbook/Closure/Closure"
          }
        ]
      },
      {
        "title": "事件循环",
        "path": "/handbook/EventLoop/EventLoop",
        "collapsable": false,
        "children": [
          {
            "title": "事件循环",
            "path": "/handbook/EventLoop/EventLoop"
          },
          {
            "title": "Promise",
            "path": "/handbook/EventLoop/Promise"
          }
        ]
      },
      {
        "title": "常用数组操作方法",
        "path": "/handbook/Array/Array",
        "collapsable": false,
        "children": [
          {
            "title": "常用数组操作方法",
            "path": "/handbook/Array/Array"
          }
        ]
      },
      {
        "title": "常用字符串操作方法",
        "path": "/handbook/String/String",
        "collapsable": false,
        "children": [
          {
            "title": "常用字符串操作方法",
            "path": "/handbook/String/String"
          }
        ]
      },
      {
        "title": "操作符优先级",
        "path": "/handbook/Operator/Operator",
        "collapsable": false,
        "children": [
          {
            "title": "操作符优先级",
            "path": "/handbook/Operator/Operator"
          }
        ]
      },
      {
        "title": "数据类型转换",
        "path": "/handbook/DataType/DataType",
        "collapsable": false,
        "children": [
          {
            "title": "数据类型转换",
            "path": "/handbook/DataType/DataType"
          }
        ]
      },
      {
        "title": "前端路由",
        "path": "/handbook/Router/Router",
        "collapsable": false,
        "children": [
          {
            "title": "前端路由",
            "path": "/handbook/Router/Router"
          }
        ]
      }
    ]
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}